name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: echo "This workflow was triggered manually."
      - name: Print the GitHub event
        run: |
          echo "Event: ${{github.event_name}}"
          echo "Repository: ${{github.ref_base}}"
          echo "Actor: ${{github.actor}}"
