# .github/workflows/manual_workflow.yml
name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      rule_name:
        description: "Rule name. If multiple rules, then use comma separator"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: echo "This workflow was triggered manually."
      - name: Print the GitHub event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.ref_base }}"
          echo "Actor: ${{ github.actor }}"

  call_workflow:
    uses: Phemix/TrynaLearnGitAndDocker/.github/workflows/femi_workflow.yml@07e2abd1c70fbf0531a899d32960fb2b8057aee9
    with:
      Command: 'pull'
      branch_name: 'main'
      rule_name: 'example-rule'
      author: 'example-author'
