name: Manual Trigger Workflow


on:
  workflow_dispatch:
    inputs:
      rule_name:
        description: "Rule name. If multiple rules, then use comma sepparator"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: echo "This workflow was triggered manually."
      - name: Print the GitHub event
        run: |
          echo "Event: ${{github.event_name}}"
          echo "Repository: ${{github.ref_base}}"
          echo "Actor: ${{github.actor}}"
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print the secret
        env:
          MY_SECRET: ${{ secrets.FEMI_TEST_SECRET}}
        run: |
          echo "The secret is: $MY_SECRET"
  call_workflow:
      # change @main to the branch name to source the CI file from
      uses: Phemix/TrynaLearnGitAndDocker/.github/workflows/callable_worfklow.yml@main
      with:
        Command: 'pull'
