name: Notify Teams on Pull Request (Delegated)

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Teams via Delegated Token
        run: |
          # Exchange refresh token for an access token
          ACCESS_TOKEN=$(curl -s -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&refresh_token=${{ secrets.REFRESH_TOKEN }}&grant_type=refresh_token&scope=https://graph.microsoft.com/.default" \
            https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/v2.0/token | jq -r .access_token)

          # Fail if token was not retrieved
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to retrieve access token"
            exit 1
          fi

          # Send the PR message to the Teams chat
          curl -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": {\"contentType\": \"html\", \"content\": \"🔔 New PR: <a href='${{ github.event.pull_request.html_url }}'>${{ github.event.pull_request.title }}</a>\"}}" \
            https://graph.microsoft.com/v1.0/chats/${{ secrets.CHAT_ID }}/messages
