name: Notify Teams on Pull Request

on:
  pull_request:
    types: [opened]   # You can adjust which PR events trigger it

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Teams
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               -d "{\"text\": \"New PR by ${{ github.event.pull_request.user.login }}: ${{ github.event.pull_request.html_url }}\"}" \
               https://teams.live.com/l/invite/FAA4JEoNvtPZp7luwI
